development:
  adapter: postgresql
  encoding: unicode
  database: coenterprise_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: coenterprise_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: coenterprise_production
  pool: 5
  username: postgres
  password:

